library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
motor <- as.character(SCC$SCC[grepl("Motor",SCC$Short.Name)])
data <- filter(NEI, SCC %in% motor, fips == "24510")
plot5data <- aggregate(data[4], by=list(data$year), FUN=sum, na.rm=TRUE)
yrange = range(0,12)
plot(plot5data, type = "h", col = "orange", ylim = yrange, main = "Motor vehicle related emission in Baltimore city", xlab = "Year", ylab = "Emission (in tons)" , xaxt = "n", lwd = 10)
axis(1,plot5data$Group.1)
dev.copy(png, "plot5.png", width=480, height=480, units="px")
dev.off()