library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
motor <- as.character(SCC$SCC[grepl("Motor",SCC$Short.Name)])
dataBc <- filter(NEI, SCC %in% motor, fips == "24510")
dataLa <- filter(NEI, SCC %in% motor, fips == "06037")
plot6dataBc <- aggregate(dataBc[4], by=list(dataBc$year), FUN=sum, na.rm=TRUE)
plot6dataLa <- aggregate(dataLa[4], by=list(dataLa$year), FUN=sum, na.rm=TRUE)
yrange = range(0,100)
plot(plot6dataBc, type = "b", col = "dark green", ylim = yrange, main = "Motor vehicle related emission.", xlab = "Year", ylab = "Emission (in tons)" , xaxt = "n", lwd = 6)
lines(plot6dataLa, type="b", col = "dark blue", ylim=yrange, lwd = 6)
axis(1,plot6dataBc$Group.1)
legend("topleft", c("Baltimore City", "LA County"), cex=0.7, col=c("dark green", "dark blue"), lty=6, bty="n")
dev.copy(png, "plot6.png", width=480, height=480, units="px")
dev.off()